name: Push Checks
on: push
jobs:
  format:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Poetry environment
        uses: ./.github/actions/setup-env
      - name: Run black
        run: poetry run black --check src
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Poetry environment
        uses: ./.github/actions/setup-env
      - name: Run pylint
        run: poetry run pylint src
  typecheck:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Poetry environment
        uses: ./.github/actions/setup-env
      - name: Run mypy
        run: poetry run mypy src
  run-help:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Poetry environment
        uses: ./.github/actions/setup-env
      - name: Run musedash-ripper-cli --help
        run: poetry run musedash-ripper-cli --help
